language: go
go:
 - 1.1.2
 - 1.1.1
 - 1.1
 - tip

install:
 - export PATH=$HOME/gopath/bin:$PATH
 - go get -v github.com/axw/gocov
 - go install github.com/axw/gocov/gocov
 - go get -v github.com/golang/glog
 - go get -v launchpad.net/gocheck
 - go get -v github.com/mailgun/gocql

script:
 - go test -v ./...
 - gocov test -deps -exclude-goroot | gocov report
